name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build Linux
      run: go build -v .
      
    - name: Build MacOS
      run: env GOOS=darwin go build -v .
      
    - name: Build Windows
      run: env GOOS=windows go build -v .
